server {
    listen 80;

    location /mailstoday.json {
        alias /shared/mailstoday.json;
        add_header Cache-Control "no-cache";
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ =404;
    }
}
